#! /bin/bash
#Adds Mass Users with input file.
read USERNAME
while [ $USERNAME != "" ] 2> /dev/null
do
read FULLNAME
#useradd -c "$FULLNAME" -m -p "ivcc2017" -s /bin/bash $USERNAME 
./aou $USERNAME $FULLNAME
read USERNAME
done
