#! /bin/bash
#gets folders from other server
#4/3/2019

mkdir /mnt/$1

sshfs -o allow_other snoopy@10.0.2.15:/$1 /mnt/$1

echo "sshfs#snoopy@10.0.2.15:/$1 /mnt/$1 fuse.sshfs defaults 0 0" >> /etc/fstab